### ISSUE TITLE
Group B: Roman Amphitheaters using RawGraphs.io

### ISSUE THREAD

**Issue by Ellis307** [SASDigitalHumanitiesTraining/Visualisation#10]
Hello! Could I have some advice?

I'm in the group looking at Roman Amphitheaters in RawGraphs.io, but haven't been able to get the website to do anything when I copy and paste the dataset into it. I thought I might have done something wrong and so I pasted the early women graduates dataset into rawgraphs and it 'successfully parsed'. I'm hoping the point is that 'it is difficult to know where you've gone wrong'?

**Comment by jonathanblaney** [comment]
@Ellis307 

It can be difficult if the site doesn't give you any feedback, like a parsing error and a line number.

In these cases I start by seeing what I can get to parse. You've already done that with the grads data so I would try cutting down the Amphitheaters data into a couple of lines and see if you can get that to parse.

**Comment by gabrielbodard** [comment]
Just for the record, I'm replicating this problem, and the Amphitheatres data doesn't seem to parse, but with such an absence of error message that at first I thought I just hadn't found the "submit" button or something. I followed Jonathan's advice and just pasted in a few lines, but it doesn't seem to parse even just the first line.

(╯°□°)╯︵ ┻━┻

I would suggest playing with a different dataset (e.g. the Mithraea) in the meantime, just to get some experience with Rawgraphs.

**Comment by jonathanblaney** [comment]
I manage to get this to parse but in a slightly cumbersome way:

1. Pasted the data into a text editor, eg Atom or Notepad, and saved it as amph.csv
2. Opened that file in Excel and saved it again as amph.xslx
3. Upload the Excel-format file to RawGraphs.

I'm guessing that RawGraphs is having a problem with a delimiter - telling the difference between a comma separating actual values and one used within values. Excel seems to enforce a choice in these cases, which at least makes the file parse. But I'm not sure that's the explanation.

**Comment by gabrielbodard** [comment]
Interesting. I got that to work just by opening the downloaded csv directly in Excel (not sure why you needed the cut and paste step first?). (I was also able to paste the content directly from Excel.) I wonder what the text file is b0rking? (I don't see any commas in the XSLX, but that may be because it's fixed them, as Jonathan suggests…)

**Comment by jonathanblaney** [comment]
Great, that method is more streamlined (I was using Edge on my work laptop and it's not obvious how you can download a page; I really need to change my default browser).

**Comment by Ellis307** [comment]
It is working now, thank you very much!

**Comment by gabrielbodard** [comment]
A question for the Amphitheatres groups (in case you have time to look at this again before the session, or want to answer later): could you use a visualisation to test the hypothesis that there is a correlation between theatre capacity and altitude?

**Comment by Ellis307** [comment]
There does seem to be quite a strong correlation between theatre capacity and altitude. Altitude has little to no effect for theatres under 20,000 capacity, but there is a clear drop off beyond this figure. (The X axis is capacity, and Y axis elevation)
![Filename](https://user-images.githubusercontent.com/66776609/85018203-b1706300-b164-11ea-8102-c99bbd8a5799.png)

**Comment by Ellis307** [comment]
Beeswarm - capacity on X Axis, second century as colour
![Filename (1)](https://user-images.githubusercontent.com/66776609/85025486-5db74700-b16f-11ea-870e-cb44d08a94c6.png)

Contour Map with labels (X axis – longitude, Y axis – latitude)

![Contour with labels](https://user-images.githubusercontent.com/66776609/85025637-8b9c8b80-b16f-11ea-985a-a7509c4e69c4.png)

Contour Map without labels (X axis – longitude, Y axis – latitude)

![Contour without labels](https://user-images.githubusercontent.com/66776609/85025648-8e977c00-b16f-11ea-8081-6ce51e3a4cbc.png)

**Comment by Jmuccigr** [comment]
> There does seem to be quite a strong correlation between theatre capacity and altitude. Altitude has little to no effect for theatres under 20,000 capacity, but there is a clear drop off beyond this figure. (The X axis is capacity, and Y axis elevation)
> ![Filename](https://user-images.githubusercontent.com/66776609/85018203-b1706300-b164-11ea-8102-c99bbd8a5799.png)

Well, I’d agree there’s no correlation for 20k and below capacity. Then there are no 20k+ amphitheaters much above sea level.

Anybody got urban population v altitude?
