### ISSUE TITLE
Group 1: Early Melville Texts 

### ISSUE THREAD

**Issue by jlvenner** [SASDigitalHumanitiesTraining/Visualisation#11]
Hi, Jess here.

My visualisation for the Melville exercise:
[url](https://voyant-tools.org/?corpus=a68f14935b0b61540758d8b00fcae946&stopList=keywords-3aacbd234b5ee471347747ea809c262c&bins=300&query=like&query=old&query=long&query=little&query=time&docId=96572cff6a72b3f6bf53d22b81f9c495&docId=242b15e1635964b6db4bc7cc2588ee0f&docId=5c79dc93dc08ef8d70f4851062a0c131&view=Bubblelines)

I chose to focus on a couple of words that I had found key in other visualisations to look at their use over time in each text, and their frequency of use. I felt that the line bubble visualisation allowed me to do this most effectively.

**Comment by cmohge1** [comment]
Thanks, that is an interesting vis. Did it generate any questions for you? Any aids for how you might read these texts/this period? (The word 'like' for example is often one of those tricky words--is it a stop word?)

**Comment by jlvenner** [comment]
Absolutely. At first, I thought 'like' may be misleading, but it revealed a tendency of Melville to use a lot of similes in his text. I looked into this further using the tool in the bottom right hand corner and found that many of these were humans being likened to animals, for example dolphins or hawks. The top visualisation for Mardi also points towards a journey/adventure - if you add sea to the visualisations, this term is used heavily at the start of the journey, while 'old' becomes more frequent towards the end. A passing of time and place, perhaps.
