### ISSUE TITLE
Group A: Roman Amphitheaters with Tableau

### ISSUE THREAD

**Issue by CarloEmilioBiuzzi** [SASDigitalHumanitiesTraining/Visualisation#14]
We have created some interactive graphs so we have decided to leave them in a Tableau format! 
[roman-amphitheaters.twb.zip](https://github.com/SASDigitalHumanitiesTraining/Visualisation/files/4798031/roman-amphitheaters.twb.zip)

**Comment by gabrielbodard** [comment]
I couldn't open that because I was using the desktop version of Tableau. Maybe you can show them to us in the session this afternoon?

**Comment by gabrielbodard** [comment]
A question for the Amphitheatres groups (in case you have time to look at this again before the session, or want to answer later): could you use a visualisation to test the hypothesis that there is a correlation between theatre capacity and altitude?

**Comment by CarloEmilioBiuzzi** [comment]
> I couldn't open that because I was using the desktop version of Tableau. Maybe you can show them to us in the session this afternoon?

Yes absolutely!

**Comment by CarloEmilioBiuzzi** [comment]
> A question for the Amphitheatres groups (in case you have time to look at this again before the session, or want to answer later): could you use a visualisation to test the hypothesis that there is a correlation between theatre capacity and altitude?

We have done a graph that shows exactly this correlation!
