### ISSUE TITLE
Group D: Early Women Graduates in RAWgraphs

### ISSUE THREAD

**Issue by kroncolleen** [SASDigitalHumanitiesTraining/Visualisation#15]
Hi Folks, 
We (Jess, Jordan, and I) had a look at the Early Women Graduates dataset using RAWGraphs: 
We've added the visualizations we want to talk about today to this Google Slides presentation: [url](https://docs.google.com/presentation/d/1VzT2p-lzEpe4L5kq7RujOlSDLMKp_64_fO5k_Acss5E)

**Comment by gabrielbodard** [comment]
Excellent idea to use Slides like this. Thanks!
