### ISSUE TITLE
Group C: Early Women Graduates in Tableau

### ISSUE THREAD

**Issue by soneill-language-arts** [SASDigitalHumanitiesTraining/Visualisation#16]

**Comment by soneill-language-arts** [comment]
https://public.tableau.com/profile/soneill#!/vizhome/EarlyWomenGraduatesEigencentralitybySchool/Dashboard1?publish=yes

https://public.tableau.com/profile/soneill#!/vizhome/EarlyWomenGraduatesEigencentrality/Dashboard2?publish=yes

Soneill visualisations focussing on Eigencentrality

**Comment by kemcclin** [comment]
<img width="1280" alt="Screen Shot 2020-06-18 at 8 23 32 AM" src="https://user-images.githubusercontent.com/67105725/85020003-ae15b100-b13d-11ea-9134-87bdca3d2df3.png">
<img width="1280" alt="Screen Shot 2020-06-18 at 7 00 57 AM" src="https://user-images.githubusercontent.com/67105725/85020023-b5d55580-b13d-11ea-9190-3c5df4dfb5a2.png">

**Comment by SePoQueR** [comment]
Ook, there is something wrong with my visualisation. It looks like my Tableau cannot work out the data as yours does, maybe? I'm really struggling with that? 
Look: https://public.tableau.com/profile/simona4613#!/vizhome/Subjectorschoolandyear/Dashboard1?publish=yes 
And: 
[doc2.pdf](https://github.com/SASDigitalHumanitiesTraining/Visualisation/files/4798574/doc2.pdf)
This is how it looks like! It seems it doesn't get the data right?
