### ISSUE TITLE
Responses to Drucker & Risam papers

### ISSUE THREAD

**Issue by gabrielbodard** [SASDigitalHumanitiesTraining/Visualisation#2]
Please add here any thoughts that we have already discussed or that you would like to add to the discussion on the two papers we discussed in the Wednesday session.

* Johanna Drucker, “Humanities Approaches to Graphical Display,” _Digital Humanities Quarterly_ (2011). Retrieved from http://digitalhumanities.org/dhq/vol/5/1/000091/000091.html
* Risam, R. (2019). Beyond the Migrant “Problem”: Visualizing Global Migration. _Television & New Media_, 20(6), Pp. 566–580.

**Comment by soneill-language-arts** [comment]
We've been thinking about ourselves as producers of visualisations. But to flip that around, how could we use this awareness of how data visualisations are produced in our critical consumption of visualisations? Thinking about the intent of the composer, what details he or she has chosen to include and why, what he or she has left out and why. It's often trickier to spot what's missing than to spot what's there, and we often find ourselves, as readers/viewers, dependent on the context provided for us by the author/composer. In a way, the visualisation is a barrier between us and the raw data, limiting our ability to engage critically with the information and increasing our dependency on the author/composer's interpretation.
As data visualisers, can we liberate our reader/viewer from that dependency?
