### ISSUE TITLE
Viz Q1: Advantages of tools

### ISSUE THREAD

**Issue by gabrielbodard** [SASDigitalHumanitiesTraining/Visualisation#3]
What were the advantages/limitations of these tools in relation to the types of visualisation you wanted to create?

**Comment by soneill-language-arts** [comment]
I had some technical issues with both the tools I used:

The online version of Voyant was quite unstable for me, perhaps it needed a bandwidth or speed I couldn't provide. This led to frozen panes and loading bars every time I made changes to a visualisation.

I also used Tableau, but found that it didn't read the CSV accurately. I converted the CSV to Excel first, and then uploaded the spreadsheet.

In terms of the visualisations I wanted to create, I found Voyant gave me great insight into the texts at word level, but I would love to be able to do more with words in context, beyond co-occurrence and collocations.
