### ISSUE TITLE
Viz Q3: Challenges

### ISSUE THREAD

**Issue by gabrielbodard** [SASDigitalHumanitiesTraining/Visualisation#5]
What challenges did you encounter with the datasets themselves and did you have to make any changes to the CSV/text files to produce more effective visualisations?

**Comment by soneill-language-arts** [comment]
I cleaned the Early Women Graduates file to remove any incomplete entries, and staff entries, so I was focussing only on the graduates.

I found that Tableau did not read my CSV correctly when I imported the raw text, so I imported the CSV to Excel first, cleaned it in Excel, and then imported the spreadsheet to Tableau
